const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./config/routes.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "Knowledge API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Users",
      description: "Endpoints",
    },
    {
      name: "Categories",
      description: "Endpoints",
    },
    {
      name: "Articles",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: ".env File",
    },
  },
  definitions: {
    User: {
      name: "Junior Barros",
      email: "junior@mail.com",
      admin: "true",
      password: "123456",
      confirmPassword: "123456",
    },
    Article: {
      name: "10 motivos para não usar Angular 12dasdas",
      description: "o artigo aborda os aespectrs",
      userId: 1,
      categoryId: 4,
      content: "Conteudo do artigo",
    },
    Categories: {
      name: "React Native",
      parentId: 3,
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./index.js");
});
